# Generated by Django 5.2.16 on 2026-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(default='Ghana', max_length=150)),
                ('period', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education Histories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(default='Ghana', max_length=150)),
                ('period', models.CharField(max_length=100)),
                ('experience_type', models.CharField(choices=[('academic', 'Academic & Teaching'), ('industry', 'Professional Surveying & Industry')], db_index=True, default='academic', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Surv. Dr. Abubakar Sadiq Mohammed (PhD)', max_length=150)),
                ('title', models.CharField(default='Lecturer & Professional Facilities Management Surveyor', max_length=200)),
                ('ghis_number', models.CharField(default='GhIS Member: VESD – 2599', max_length=100)),
                ('department', models.CharField(default='Department of Building Technology', max_length=200)),
                ('institution', models.CharField(default='Accra Technical University, Ghana', max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='drsadick@kpce.edu.gh', max_length=254)),
                ('phone', models.CharField(default='+233544966668', max_length=30)),
                ('whatsapp_number', models.CharField(default='233544966668', help_text='Format: 233544966668 without + sign', max_length=30)),
                ('office_address', models.CharField(default='Kibi Presbyterian College of Education & Accra Technical University', max_length=255)),
                ('citations_count', models.IntegerField(db_index=True, default=179)),
                ('google_scholar_url', models.URLField(default='https://scholar.google.com/citations?user=hMUoZnQAAAAJ&hl=en')),
                ('researchgate_url', models.URLField(default='https://www.researchgate.net/profile/Abubakar-Mohammed-27')),
                ('kpce_directory_url', models.URLField(default='https://directory.kpce.edu.gh/personnel/surv-mohammed-abubakar-sadiq/')),
            ],
            options={
                'verbose_name': 'Profile Information',
                'verbose_name_plural': 'Profile Information',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('authors', models.CharField(max_length=350)),
                ('journal_or_conference', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(db_index=True)),
                ('citations_count', models.IntegerField(db_index=True, default=0)),
                ('category', models.CharField(db_index=True, help_text='Category tag e.g. Smart FM, Mosque Operations, Healthcare, Education', max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('google_scholar_link', models.URLField(blank=True, null=True)),
                ('researchgate_link', models.URLField(blank=True, null=True)),
                ('doi_link', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-year', '-citations_count', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('icon_name', models.CharField(default='building', help_text='Icon identifier (e.g. building, cpu, mosque, shield, users, wrench)', max_length=50)),
                ('read_more_url', models.URLField(blank=True, help_text='Direct link to ResearchGate or Scholar paper on this topic', null=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Research Interest',
                'verbose_name_plural': 'Research Interests',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
